"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { useParams } from "next/navigation";
import { api, assetUrl } from "@/lib/api";
import { Spinner, SeverityBadge, Disclosure, BackLink } from "@/components/ui";
import {
  FindingsSection,
  NutritionSection,
  RecommendationsSection,
  DoctorSection,
  type Screening,
} from "@/components/ScreeningView";

export default function ScreeningDetailPage() {
  const params = useParams();
  const id = params.id;
  const [s, setS] = useState<Screening | null>(null);
  const [err, setErr] = useState("");

  useEffect(() => {
    api<{ screening: Screening }>(`/api/history/${id}`)
      .then((d) => setS(d.screening))
      .catch((e) => setErr(e.message));
  }, [id]);

  const download = async () => {
    const res = await api<Response>(`/api/reports/${id}/pdf`, { isBlob: true });
    const blob = await res.blob();
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `dermai_screening_${id}.pdf`;
    a.click();
    URL.revokeObjectURL(url);
  };

  if (err) return <div className="container page"><div className="alert alert-danger">{err}</div></div>;
  if (!s) return <div className="container page"><Spinner /></div>;

  const symptoms = s.symptoms as
    | { answers?: Record<string, unknown> }
    | Record<string, unknown>
    | null
    | undefined;
  const answers = (symptoms?.answers || symptoms || {}) as Record<string, unknown>;
  const diet = s.diet_info || {};
  const findings = s.predictions?.findings || {};

  const showScalp = s.scalp_image_path || findings.scalp;
  const showNails = s.nail_image_path || findings.nails;

  return (
    <div className="container page">
      <div className="flex-between mb-2">
        <BackLink to="/history" label="Back to History" />
        <div className="flex-center">
          <button className="btn btn-primary btn-sm" onClick={download}>Download PDF report</button>
        </div>
      </div>
      <h1 className="page-title">Screening #{s.id}</h1>
      <p className="page-sub">
        {s.created_at} · {s.screening_type} screening ·{" "}
        {s.mode === "real" ? "Real CNN" : "Demo / Prototype"} mode
      </p>

      {s.mode !== "real" && (
        <div className="demo-banner">
          DEMO / PROTOTYPE AI RESULT — generated by the built-in prototype engine,
          not a trained medical CNN.
        </div>
      )}

      <div className={`result-hero ${(s.overall_severity || "low").toLowerCase()} mb-3`}>
        <div className="result-title">{s.overall_condition}</div>
        <div>{s.summary_text}</div>
        <div className="result-meta">
          <span>Confidence: {(s.overall_confidence * 100).toFixed(0)}%</span>
          <span>Severity: <SeverityBadge severity={s.overall_severity} /></span>
        </div>
      </div>

      {(showScalp || showNails) && (
        <>
          <h2 className="section-title">Uploaded images</h2>
          <div className="grid grid-2">
            {showScalp && (
              <div className="card center">
                <b className="small">Scalp / hair</b>
                {s.scalp_image_path ? (
                  <img className="preview-img" src={assetUrl(`/uploads/${s.scalp_image_path}`)} alt="Scalp" />
                ) : (
                  <p className="small muted">No scalp image uploaded.</p>
                )}
              </div>
            )}
            {showNails && (
              <div className="card center">
                <b className="small">Nail</b>
                {s.nail_image_path ? (
                  <img className="preview-img" src={assetUrl(`/uploads/${s.nail_image_path}`)} alt="Nail" />
                ) : (
                  <p className="small muted">No nail image uploaded.</p>
                )}
              </div>
            )}
          </div>
        </>
      )}

      <h2 className="section-title">Symptom responses</h2>
      <div className="card">
        <div className="grid grid-2">
          {Object.entries(answers)
            .filter(([k]) => !k.includes("flag"))
            .map(([k, v]) => (
              <div key={k} className="small" style={{ borderBottom: "1px solid var(--slate-100)", padding: "0.3rem 0" }}>
                <span className="muted">{prettyKey(k)}:</span> <b>{prettyVal(v)}</b>
              </div>
            ))}
        </div>
        {Object.keys(diet).length > 0 && (
          <p className="small muted mt-2">
            Lifestyle/diet recorded for this screening.
          </p>
        )}
      </div>

      <h2 className="section-title">Explainability</h2>
      <div className="card">
        <p className="small muted">
          Explainability visualization (Grad-CAM heatmap) will become available
          when the trained CNN model is connected. In demo mode, no fake medical
          heatmaps are displayed.
        </p>
      </div>

      <h2 className="section-title">Multimodal results</h2>
      <FindingsSection findings={findings} />

      <h2 className="section-title">Recommendations</h2>
      <RecommendationsSection rec={s.recommendations} />

      <h2 className="section-title">Nutrition &amp; hydration</h2>
      <NutritionSection nutrition={s.nutrition_insights} />

      <h2 className="section-title">Doctor recommendation</h2>
      <DoctorSection docrec={s.doctor_recommendation} />

      <div className="mt-3">
        <Disclosure />
      </div>
    </div>
  );
}

function prettyKey(k: string) {
  return k.replace(/_/g, " ");
}

function prettyVal(v: unknown) {
  if (v === true) return "Yes";
  if (v === false) return "No";
  return String(v);
}